name: Build/upload tools

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 UTC on the 1st of every month

jobs:
  MAME-AMD64:
    name: Build mame-tools AMD64
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        run: |
          latest_tag=$(curl -s "https://api.github.com/repos/mamedev/mame/releases/latest" | jq -r '.tag_name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
    
      - name: Enable source repositories
        run: |
          source /etc/os-release
          echo "deb-src http://azure.archive.ubuntu.com/ubuntu $VERSION_CODENAME main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://azure.archive.ubuntu.com/ubuntu $VERSION_CODENAME-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://security.ubuntu.com/ubuntu $VERSION_CODENAME-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          sudo apt update
          
      - name: Install dependencies
        run: |
            sudo apt build-dep mame-tools -y
            sudo apt install wget

      - name: wget latest mame repo release
        run: |
          wget https://github.com/mamedev/mame/archive/refs/tags/${{ env.LATEST_TAG }}.zip
          unzip ${{ env.LATEST_TAG }}.zip
          rm ${{ env.LATEST_TAG }}.zip
          mv mame-* mame

      - name: Build mame-tools
        run: |
          cd mame
          make TOOLS=1 EMULATOR=0 -j4
          mv chdman ../chdman-AMD64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chdman-AMD64-${{ env.LATEST_TAG }}
          path: chdman-AMD64

  MAME-ARM64:
      name: Build mame-tools ARM64
      runs-on: ubuntu-24.04-arm
      steps:
      - name: Get tag
        run: |
          latest_tag=$(curl -s "https://api.github.com/repos/mamedev/mame/releases/latest" | jq -r '.tag_name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
    
      - name: Enable source repositories
        run: |
          source /etc/os-release
          echo "deb-src http://azure.archive.ubuntu.com/ubuntu $VERSION_CODENAME main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://azure.archive.ubuntu.com/ubuntu $VERSION_CODENAME-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://security.ubuntu.com/ubuntu $VERSION_CODENAME-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          sudo apt update
          
      - name: Install dependencies
        run: |
            sudo apt build-dep mame-tools -y
            sudo apt install wget
            
      - name: wget latest mame repo release
        run: |
          wget https://github.com/mamedev/mame/archive/refs/tags/${{ env.LATEST_TAG }}.zip
          unzip ${{ env.LATEST_TAG }}.zip
          rm ${{ env.LATEST_TAG }}.zip
          mv mame-* mame
          
      - name: Build mame-tools
        run: |
          cd mame
          make TOOLS=1 EMULATOR=0 -j4
          mv chdman ../chdman-ARM64
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chdman-ARM64-${{ env.LATEST_TAG }}
          path: chdman-ARM64

  DTools-AMD64:
      name: Build dolphin-tools AMD64
      runs-on: ubuntu-latest
      steps:
      - name: Enable source repositories
        run: |
          source /etc/os-release
          echo "deb-src http://azure.archive.ubuntu.com/ubuntu $VERSION_CODENAME main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://azure.archive.ubuntu.com/ubuntu $VERSION_CODENAME-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://security.ubuntu.com/ubuntu $VERSION_CODENAME-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          sudo apt update
          
      - name: Install dependencies
        run: |
            sudo apt build-dep dolphin -y
            sudo apt install wget libxrandr-dev libxi-dev ffmpeg libudev-dev build-essential git cmake ffmpeg libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libevdev-dev libusb-1.0-0-dev libxrandr-dev libxi-dev libpangocairo-1.0-0 qt6-base-private-dev libqt6svg6-dev libbluetooth-dev libasound2-dev libpulse-dev libgl1-mesa-dev libcurl4-openssl-dev
            
      - name: clone dolphin repo
        run: |
          git clone --recursive https://github.com/dolphin-emu/dolphin
          
      - name: Build dolphin-tools
        run: |
          cd dolphin
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          cd Binaries
          mv dolphin-tool $GITHUB_WORKSPACE/dolphin-tool-AMD64
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolphin-tool-AMD64
          path: dolphin-tool-AMD64

  DTools-ARM64:
      name: Build dolphin-tools ARM64          mv chdman-AMD64 ../chdman-AMD64
      runs-on: ubuntu-24.04-arm
      steps:
      - name: Enable source repositories
        run: |
          source /etc/os-release
          echo "deb-src http://azure.archive.ubuntu.com/ubuntu $VERSION_CODENAME main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://azure.archive.ubuntu.com/ubuntu $VERSION_CODENAME-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://security.ubuntu.com/ubuntu $VERSION_CODENAME-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          sudo apt update
          
      - name: Install dependencies
        run: |
            sudo apt build-dep dolphin -y
            sudo apt install wget libxrandr-dev libxi-dev ffmpeg libudev-dev build-essential git cmake ffmpeg libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libevdev-dev libusb-1.0-0-dev libxrandr-dev libxi-dev libpangocairo-1.0-0 qt6-base-private-dev libqt6svg6-dev libbluetooth-dev libasound2-dev libpulse-dev libgl1-mesa-dev libcurl4-openssl-dev
            
      - name: clone dolphin repo
        run: |
          git clone --recursive https://github.com/dolphin-emu/dolphin
          
      - name: Build dolphin-tools
        run: |
          cd dolphin
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          cd Binaries
          mv dolphin-tool $GITHUB_WORKSPACE/dolphin-tool-ARM64
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolphin-tool-ARM64
          path: dolphin-tool-ARM64

  release:
    needs: [MAME-AMD64, MAME-ARM64, DTools-AMD64, DTools-ARM64]
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        run: |
          latest_tag=$(curl -s "https://api.github.com/repos/mamedev/mame/releases/latest" | jq -r '.tag_name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Set date variables
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

          
      - name: Download Artifact One
        uses: actions/download-artifact@v4
        with:
          name: chdman-AMD64-${{ env.LATEST_TAG }}
          path: artifacts

      - name: Download Artifact Two
        uses: actions/download-artifact@v4
        with:
          name: chdman-ARM64-${{ env.LATEST_TAG }}
          path: artifacts

      - name: Download Artifact Three
        uses: actions/download-artifact@v4
        with:
          name: dolphin-tool-AMD64
          path: artifacts

      - name: Download Artifact Four
        uses: actions/download-artifact@v4
        with:
          name: dolphin-tool-ARM64
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Tools ${{ steps.date.outputs.date }}"
          tag_name: "Tools-${{ steps.date.outputs.date }}"
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
